### ISSUE TITLE
Package declarations not matching actual file path

### ISSUE THREAD

**Issue by Tschaeggie** [GraxCode/JByteMod-Beta#18]
Please change the package declarations to match the actual path of the java file.
Following the [standardized maven project layout](http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) makes the project easier to use, build and contribute to.

**Comment by GraxCode** [comment]
Can you give me an example for a correct package declaration? I think everything is right as it is now

**Comment by Tschaeggie** [comment]
Nevermind i messed up my IDE settings. I marked the wrong folder as "sourceFolder" while importing.
