### ISSUE TITLE
would be nice to provide more command line args

### ISSUE THREAD

**Issue by jprogramer** [GraxCode/JByteMod-Beta#25]
I like JByteMod so much, and I would be cool to just double-click a class file and have it opened with the class file loaded...
basically, just support a few more arguments, so instead of running JByteMod like this
`java -jar target/JByteMod-1.5.1.jar [working dir]`
it would be more flexible to run it like this:
`java -jar target/JByteMod-1.5.1.jar [working dir] [*.jar or *.class to load]`
or even better:
`java -jar target/JByteMod-1.5.1.jar [working dir] [*.jar or *.class to load] [config file path] [plugin dir]`

by the way, I have no idea what is that "working dir" (tried to pass the dir of my .class file here, but it wasn't loaded) so you can show some love and print a simple help when someone passes a -help argument (or an illegal argument)...

sorry to bother you and, hope that u keep up the great work!

**Comment by jprogramer** [comment]
thx dude ur the best!

**Comment by jprogramer** [comment]
could you please release a new version soon, it has been a week since you've added the CLI but no version that includes it has been released yet, I feel like you've forgotten to release a new binaries
in case the feature is still not ready to be released yet, maybe it's a good idea to remove the CLI from the docs for now

**Comment by GraxCode** [comment]
i'll be releasing it soon, but you could always build it yourself!

**Comment by jprogramer** [comment]
Thank you, I'm looking forward to it!
also, I've tried to build it but it seems that it's not compatible with JDK 9, even after adding the look and feel jar, removing CFR decompiler and setting illegal access to "warn" I couldn't build it
becuase some classes from tools.jar was missing (I thought JDK 9 include such classes in its own runtime modules...whatever...) and I won't include a tool.jar from a JDK 8, it just feels wrong to me, then I just decided that resolving any more dependencies is a headache and I gave up :3
