### ISSUE TITLE
Procyon decompiler doesn't work

### ISSUE THREAD

**Issue by mendax47** [GraxCode/JByteMod-Beta#27]
when i chose procyon decompiler it stuck at loading (Forever)....... 

https://imgur.com/a/bUyXU

**Comment by GraxCode** [comment]
Could you please post your console log and java version?

**Comment by GraxCode** [comment]
try again now

**Comment by mendax47** [comment]
I am so sorry.. i just didn't saw that first issue... in that issue you clearly mention that Procyon doesn't work in java 9... and i have java 9 only after removing 9 and installing 8 i fixed the problem... THANKS..

**Comment by GraxCode** [comment]
Did you try using the latest build with java 9?

**Comment by mendax47** [comment]
No.. I was using 1.6.0 was last released 12 days ago...

**Comment by GraxCode** [comment]
Java 9 should work with the latest build, please check
