### ISSUE TITLE
It would be nice to have a "Reload" button that reload files from the disk

### ISSUE THREAD

**Issue by jprogramer** [GraxCode/JByteMod-Beta#30]
when I recompile my binaries, I need to close JByteMod and reopen it again to see the changes
I thought that the reload button in decompiler tab is supposed to reload the file from the disk but it is not,
which made me think that it's just meant to re-decompile the file (or maybe it's a bug :3)
anyways it would be nice to make this button reload the file from the disk or to have another button for this purpose (possibly a global one not just for this tab)

**Comment by jprogramer** [comment]
"a shortcut for file>load that loads the exact file again" yes, please! 
I decompile my own code from time to time when I'm testing small code snippets, you know when you want that critical part to perform at least 2% better you gotta get your hand dirty and read Bytecode/Decompile
like what?  well if you are interested read this example:
`public class Test {
    static Test instance = new Test();
    public static void main(final String... arguments) {
        for (int i = 0; i < 3; i++) {
            test(() -> instance.run());
        }
        System.out.println("---------------");
        for (int i = 0; i < 3; i++) {
            test(instance::run);
        }
    }
    static void test(Runnable runnable) {
        System.out.println(runnable.hashCode());
    }
    void run() { }
}`
# and the output was:
796684896
796684896
796684896
---------------
41903949
488970385
1209271652
see? in the second loop, each iteration creates a new object!
and I needed to decompile the damn classes over and over again to understand when my lamdas (and method references) create a new instance and when they do not!
(it took me half-day to fully understand this on my own but feel free to do the same or have me email you the answer :3 at youcef-kun@hotmail.fr)
THIS WAS A HUGE MISS-USING TO GITHUB COMMENTS...I'M SORRY FOR THAT!

**Comment by GraxCode** [comment]
closing this as i don't think it is a useful feature, and you always could load using file -> load. If you only want to decompile then you should use the decompilers from their CLI.

**Comment by jprogramer** [comment]
ok, I see your point...and for the record, I've said "It would be nice" not "this is a must need feature" xd
