### ISSUE TITLE
Hel for novice

### ISSUE THREAD

**Issue by das873** [GraxCode/JByteMod-Beta#4]
Hi,
how can I install jbytemode editor? (Sorry I am a novice...)

**Comment by ItzSomebody** [comment]
You don't, you just run it

**Comment by das873** [comment]
Thank you ItzSomebody for your very promp reply!
The problem is that I am at a very novice level... With the old Jbytedit there was a simple jar file.
How run jbytemod?

**Comment by ItzSomebody** [comment]
Download file from https://github.com/GraxCode/JByteMod-Beta/releases

Unzip file then run JByteMod binary

**Comment by das873** [comment]
Thank you!
(What a dummy I am...    ;-P    I didn't seen the release folder...)

Great!

Bye!
