### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by CrackFileso** [GraxCode/JByteMod-Beta#44]
Add back Source Name Renamer(Rename source to ClassXXX.java)
Add Source Name-->ClassName
Add back Source Name Search
Add back Class Name Search(Include repeat Class Name in different Package)
System.exit & new Socket & new URL & Runtime.exit Searcher
Add back try catch block Remover
=========================
Java Code ——> Java Byte Code Helper
for the First User to use Jbytemod easy
（If not ,when you want to edit

"
i=o=9;
while(o>0)
o--;
"
to:
"
i=9;
o=i-1;
while(o<0)
o--;
"
I you don't know how to,you need to try it in eclipse.And then get the bytecode to made it work.
）

**Comment by GraxCode** [comment]
I do not quite understand what you mean with the bytecode decompiler. Do you want an editable decompiler tab that recompiles? Please try to express yourself clearly.

**Comment by SuperOP535** [comment]
> I do not quite understand what you mean with the bytecode helper. Do you want an editable decompiler tab that recompiles? Please try to express yourself clearly.

this would be nice

**Comment by CrackFileso** [comment]
yes

**Comment by CrackFileso** [comment]
if it is impossible to make,please close this issue

**Comment by GraxCode** [comment]
In my opinion, this isn't very useful. This is a bytecode editor and not an editor for decompiled code. Recompiling decompiled code would anyway result in invalid code.
