### ISSUE TITLE
Unmodified JAR size changed and doesn't execute properly after saving

### ISSUE THREAD

**Issue by ijoeleoli** [GraxCode/JByteMod-Beta#46]
I've loaded a JAR file and immediately saved it as another JAR. The file size is changed and the new JAR doesn't run properly.

**Comment by ijoeleoli** [comment]
The part of the application that doesn't run properly is the implementation of joptsimple. Using another decompiler shows that on a specific line the program instantiates OptionParser. Decompiling with JByteMod shows /* Unavailable Anonymous Inner Class!! */.

**Comment by GraxCode** [comment]
Could you send me the jar file please? (graxcoding@gmail.com)

**Comment by ijoeleoli** [comment]
Sending it now.

**Comment by ijoeleoli** [comment]
Any update?

**Comment by GraxCode** [comment]
Couldn't find any problems with JByteMod. Did you check "Use Compute Maxs"? If so, try disabling it.
If it still wont work, then the problem relies on the asm library
