### ISSUE TITLE
add a thing

### ISSUE THREAD

**Issue by helloxdd** [GraxCode/JByteMod-Beta#5]
i think you should add a live compiler while editing
practically you click on the decompiler and you can edit things and not going on code 

i dont think its possibile but hey.

**Comment by GraxCode** [comment]
That'd most likely result in wrong bytecode

**Comment by helloxdd** [comment]
bytecode-viewer have it too, but its outdated & its a little bit slow

**Comment by helloxdd** [comment]
@GraxCode what about you but the updates already compiled in release?

**Comment by GraxCode** [comment]
i'm releasing new versions when i'm done with updating
